run:
  timeout: 3m

linters:
  enable:
    - ifshort

  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused

linters-settings:
  decorder:
    disable-dec-order-check: false
    disable-init-func-first-check: false
    disable-dec-num-check: true
  errcheck:
    check-type-assertions: true
    check-blank: false
    disable-default-exclusions: false
  errchkjson:
    check-error-free-encoding: true
    report-no-exported: false
  exhaustive:
    check-generated: true
    explicit-exhaustive-switch: false
    explicit-exhaustive-map: false
    default-signifies-exhaustive: false
    package-scope-only: false
  gocyclo:
    min-complexity: 50
  godot:
    period: false
    capital: true
    check-all: false
  gofmt:
    simplify: false
    rewrite-rules:
      - pattern: "interface{}"
        replacement: "any"
      - pattern: "a[b:len(a)]"
        replacement: "a[b:]"
  gofumpt:
    extra-rules: true
  goimports:
    local-prefixes: gitlab.com/fisherprime
  gomnd:
    ignored-numbers:
      - "0666"
      - "0755"
      - "42"
  gosimple:
    checks: ["all"]
  govet:
    check-shadowing: true
    enable-all: true
    disable-all: false
  grouper:
    const-require-single-const: true
    const-require-grouping: true
    import-require-single-import: true
    import-require-grouping: true
    type-require-single-type: false
    type-require-grouping: false
    var-require-single-var: true
    var-require-grouping: true
  ifshort:
    max-decl-lines: 2
    max-decl-chars: 40
  importas:
    no-unaliased: false
    no-extra-aliases: true
    alias:
      - pkg: github.com/volatiletech/authboss/v3/oauth2
        alias: aboauth2
      - pkg: github.com/volatiletech/authboss/v3/recover
        alias: abrecover
      - pkg: github.com/go-openapi/runtime/middleware
        alias: oamiddleware
      - pkg: github.com/volatiletech/authboss-clientstate
        alias: abclientstate
      - pkg: html/template
        alias: htmltemplate
      - pkg: github.com/fabienm/go-logrus-formatters
        alias: logformatters
  maintidx:
    under: 70
  revive:
    confidence: 0.1
    rules:
      - name: package-comments
        severity: warning
        disabled: true
  staticcheck:
    checks: ["all"]
  varnamelen:
    max-distance: 6
    min-name-length: 3
    check-receiver: true
    check-return: true
    check-type-param: true
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - err
    ignore-decls:
      - c echo.Context
      - t testing.T
      - f *foo.Bar
      - e error
      - i int
      - const C
      - T any
      - m map[string]int
  whitespace:
    multi-if: true
    multi-func: true
